// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/incident-io-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"action | alert | alert_attribute | alert_note | alert_route | alert_source | api_key | catalog_entry | catalog_resource | catalog_type | catalog_type_schema | custom_field | custom_field_option | escalation | follow_up | incident | incident_alert | incident_attachment | incident_membership | incident_participant | incident_participant_workload | incident_relationship | incident_role | incident_status | incident_timestamp | incident_type | incident_update | ip_allowlist | maintenance_window | postmortem_document | schedule | schedule_entry | schedule_replica | schedule_sync_rule | schedule_sync_target | secret | severity | status_page | status_page_incident | status_page_incident_update | status_page_maintenance | status_page_maintenance_update | status_page_structure | team | telemetry_data_source | user | workflow | workflow_run"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.IncidentIoSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "incident-io_list",
		Description: "List records from IncidentIo. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "incident-io_load",
		Description: "Load a single record from IncidentIo. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.IncidentIoSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IncidentIoSDK, name string) (sdk.IncidentIoEntity, error) {
	switch strings.ToLower(name) {
	case "action":
		return client.Action(nil), nil
	case "alert":
		return client.Alert(nil), nil
	case "alert_attribute":
		return client.AlertAttribute(nil), nil
	case "alert_note":
		return client.AlertNote(nil), nil
	case "alert_route":
		return client.AlertRoute(nil), nil
	case "alert_source":
		return client.AlertSource(nil), nil
	case "api_key":
		return client.ApiKey(nil), nil
	case "catalog_entry":
		return client.CatalogEntry(nil), nil
	case "catalog_resource":
		return client.CatalogResource(nil), nil
	case "catalog_type":
		return client.CatalogType(nil), nil
	case "catalog_type_schema":
		return client.CatalogTypeSchema(nil), nil
	case "custom_field":
		return client.CustomField(nil), nil
	case "custom_field_option":
		return client.CustomFieldOption(nil), nil
	case "escalation":
		return client.Escalation(nil), nil
	case "follow_up":
		return client.FollowUp(nil), nil
	case "incident":
		return client.Incident(nil), nil
	case "incident_alert":
		return client.IncidentAlert(nil), nil
	case "incident_attachment":
		return client.IncidentAttachment(nil), nil
	case "incident_membership":
		return client.IncidentMembership(nil), nil
	case "incident_participant":
		return client.IncidentParticipant(nil), nil
	case "incident_participant_workload":
		return client.IncidentParticipantWorkload(nil), nil
	case "incident_relationship":
		return client.IncidentRelationship(nil), nil
	case "incident_role":
		return client.IncidentRole(nil), nil
	case "incident_status":
		return client.IncidentStatus(nil), nil
	case "incident_timestamp":
		return client.IncidentTimestamp(nil), nil
	case "incident_type":
		return client.IncidentType(nil), nil
	case "incident_update":
		return client.IncidentUpdate(nil), nil
	case "ip_allowlist":
		return client.IpAllowlist(nil), nil
	case "maintenance_window":
		return client.MaintenanceWindow(nil), nil
	case "postmortem_document":
		return client.PostmortemDocument(nil), nil
	case "schedule":
		return client.Schedule(nil), nil
	case "schedule_entry":
		return client.ScheduleEntry(nil), nil
	case "schedule_replica":
		return client.ScheduleReplica(nil), nil
	case "schedule_sync_rule":
		return client.ScheduleSyncRule(nil), nil
	case "schedule_sync_target":
		return client.ScheduleSyncTarget(nil), nil
	case "secret":
		return client.Secret(nil), nil
	case "severity":
		return client.Severity(nil), nil
	case "status_page":
		return client.StatusPage(nil), nil
	case "status_page_incident":
		return client.StatusPageIncident(nil), nil
	case "status_page_incident_update":
		return client.StatusPageIncidentUpdate(nil), nil
	case "status_page_maintenance":
		return client.StatusPageMaintenance(nil), nil
	case "status_page_maintenance_update":
		return client.StatusPageMaintenanceUpdate(nil), nil
	case "status_page_structure":
		return client.StatusPageStructure(nil), nil
	case "team":
		return client.Team(nil), nil
	case "telemetry_data_source":
		return client.TelemetryDataSource(nil), nil
	case "user":
		return client.User(nil), nil
	case "workflow":
		return client.Workflow(nil), nil
	case "workflow_run":
		return client.WorkflowRun(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
